import type { Eq1Client } from "../eq1/llm-client";
import { createLogger, opencodeAgent } from "../utils";
import {
    encodeTelegramTaskSource,
    extractTelegramChatIdFromTaskSource,
} from "../utils/telegram-source";
import type { Interaction, Store, Task, TaskType } from "../x2/store";
import type { InteractionEvaluation } from "../x3/evaluator";
import { summarizeInteractionContext } from "./summarizer";
import type { OpenCodeServer } from "../opencode-server-wrapper";

const logger = createLogger("X4.Router");

export interface X4RouteDecision {
    action: "report" | "new_task" | "auto_relay" | "skip";
    reason: string;
    prompt: string | null;
    raw: Record<string, unknown>;
    schema_version?: string;
    request_hash?: string;
    parent_id?: string;
}

export interface X4RouteRequest {
    schema_version: string;
    request_hash: string;
    parent_id: string;
    summary: Record<string, unknown>;
}

interface X4RouterOptions {
    server?: OpenCodeServer | null;
    summarizerAgent?: string | null;
}

const ROUTE_REQUEST_SCHEMA_VERSION = "x4_route_request.v1";
const ROUTE_RESPONSE_SCHEMA_VERSION = "x4_route_response.v1";

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

function toText(value: unknown): string | null {
    return typeof value === "string" && value.trim().length > 0 ? value : null;
}

function normalizeAction(value: unknown): X4RouteDecision["action"] | null {
    const text = toText(value)?.toLowerCase();
    if (!text) return null;
    if (text === "new_task" || text === "task" || text === "enqueue") {
        return "new_task";
    }
    if (text === "report" || text === "notify" || text === "user") {
        return "report";
    }
    if (
        text === "auto_relay" ||
        text === "relay" ||
        text === "continue" ||
        text === "continuation"
    ) {
        return "auto_relay";
    }
    if (text === "skip" || text === "none" || text === "noop") {
        return "skip";
    }
    return null;
}

function fallbackAction(
    evaluation: InteractionEvaluation,
    interactionType: Interaction["type"],
): X4RouteDecision["action"] {
    if (interactionType === "joshua_decision") return "skip";
    return evaluation.score > 6 ? "report" : "skip";
}

function buildTaskPrompt(
    action: X4RouteDecision["action"],
    summaryText: string,
    output: Record<string, unknown>,
    fallbackReason: string,
): string {
    const direct =
        toText(output.prompt) ??
        toText(output.task_prompt) ??
        toText(output.instruction) ??
        toText(output.message);
    if (direct) return direct;

    if (action === "new_task") {
        return `Follow-up task generated by X4: ${fallbackReason}`;
    }
    if (action === "auto_relay") {
        return `X4 continuation:\n${summaryText}`;
    }
    if (action === "report") {
        return `X4 report:\n${summaryText}`;
    }
    return fallbackReason;
}

function buildRouteRequest(
    interaction: Interaction,
    summary: Record<string, unknown>,
): X4RouteRequest {
    const requestHash = toText(summary.request_hash) ?? "missing";
    const parentId = toText(summary.parent_id) ?? interaction.id;
    return {
        schema_version: ROUTE_REQUEST_SCHEMA_VERSION,
        request_hash: requestHash,
        parent_id: parentId,
        summary,
    };
}

function buildRouteDecision(
    output: Record<string, unknown>,
    evaluation: InteractionEvaluation,
    interactionType: Interaction["type"],
    summary: Record<string, unknown>,
    summaryText: string,
): X4RouteDecision {
    const action =
        normalizeAction(output.action) ??
        fallbackAction(evaluation, interactionType);
    const reason =
        toText(output.reason) ??
        toText(output.route_reason) ??
        evaluation.reason;
    const prompt =
        action === "skip"
            ? null
            : buildTaskPrompt(action, summaryText, output, reason);

    return {
        action,
        reason,
        prompt,
        raw: output,
        schema_version:
            toText(output.schema_version) ?? ROUTE_RESPONSE_SCHEMA_VERSION,
        request_hash:
            toText(output.request_hash) ??
            toText(summary.request_hash as unknown) ??
            "missing",
        parent_id:
            toText(output.parent_id) ??
            toText(summary.parent_id as unknown) ??
            undefined,
    };
}

export class X4Router {
    private store: Store;
    private eq1Client: Eq1Client;
    private server: OpenCodeServer | null;
    private summarizerAgent: string | null;

    constructor(
        store: Store,
        eq1Client: Eq1Client,
        options: X4RouterOptions = {},
    ) {
        this.store = store;
        this.eq1Client = eq1Client;
        this.server = options.server ?? null;
        this.summarizerAgent = options.summarizerAgent
            ? options.summarizerAgent.trim() || null
            : null;
    }

    async routeInteraction(
        interaction: Interaction,
        evaluation: InteractionEvaluation,
    ): Promise<{ decision: X4RouteDecision; task: Task | null }> {
        const summary = summarizeInteractionContext(interaction, evaluation);
        const summaryWithLlm = await this.enrichSummaryWithAgent(summary);
        const request = buildRouteRequest(interaction, summaryWithLlm);
        const requestPayload = JSON.stringify(request, null, 2);
        const summaryText =
            toText(summaryWithLlm.llm_summary as unknown) ??
            JSON.stringify(summaryWithLlm, null, 2);

        let output: Record<string, unknown> = {};
        try {
            const result = await this.eq1Client.route(requestPayload, {
                interactionType: interaction.type,
                requestId: interaction.requestId,
                source: "x4_router",
                x4_route_request_hash: request.request_hash,
                x4_route_parent_id: request.parent_id,
            });
            output = isRecord(result.output) ? result.output : {};
        } catch (error) {
            const message =
                error instanceof Error ? error.message : String(error);
            logger.warn("x4_route_call_failed", {
                interaction: interaction.id.slice(0, 8),
                requestId: interaction.requestId,
                error: message,
            });
        }

        let decision = buildRouteDecision(
            output,
            evaluation,
            interaction.type,
            summaryWithLlm,
            summaryText,
        );

        if (
            toText(decision.request_hash) &&
            toText(output.request_hash) &&
            output.request_hash !== request.request_hash
        ) {
            logger.warn("x4_route_request_hash_mismatch", {
                interaction: interaction.id.slice(0, 8),
                expected: request.request_hash,
                observed: output.request_hash,
            });
        }

        if (decision.action === "auto_relay") {
            const relayPrompt =
                decision.prompt ?? `X4 continuation:\n${summaryText}`;
            const relayed = await this.tryAutoRelay(interaction, relayPrompt);
            if (relayed) {
                decision = {
                    ...decision,
                    prompt: relayPrompt,
                };
            } else {
                const fallback = fallbackAction(evaluation, interaction.type);
                decision = {
                    ...decision,
                    action: fallback,
                    reason: `${decision.reason} (auto_relay_unavailable)`,
                    prompt:
                        fallback === "skip"
                            ? null
                            : `X4 relay fallback report:\n${summaryText}`,
                };
            }
        }

        let task: Task | null = null;
        if (
            decision.action !== "skip" &&
            decision.action !== "auto_relay" &&
            decision.prompt
        ) {
            const type: TaskType =
                decision.action === "new_task" ? "omo_request" : "report";
            task = this.store.createTask(
                decision.prompt,
                this.resolveTaskSource(interaction),
                type,
                interaction.sessionId,
            );
        }

        logger.info("x4_route_decision", {
            interaction: interaction.id.slice(0, 8),
            requestId: interaction.requestId,
            action: decision.action,
            task: task ? task.id.slice(0, 8) : null,
            schema_version: decision.schema_version,
            request_hash: decision.request_hash,
            parent_id: decision.parent_id,
        });

        return {
            decision,
            task,
        };
    }

    private resolveTaskSource(interaction: Interaction): string {
        const baseSource = "x4";
        const sessionId = interaction.sessionId?.trim();
        if (!sessionId) return baseSource;

        const source = this.store.getTaskSourceBySessionId(sessionId);
        if (!source) return baseSource;

        const chatId = extractTelegramChatIdFromTaskSource(source);
        return encodeTelegramTaskSource(baseSource, chatId);
    }

    private async tryAutoRelay(
        interaction: Interaction,
        prompt: string,
    ): Promise<boolean> {
        if (!this.server) {
            logger.warn("x4_auto_relay_unavailable", {
                interaction: interaction.id.slice(0, 8),
                requestId: interaction.requestId,
                reason: "server_missing",
            });
            return false;
        }

        if (interaction.type === "permission") {
            logger.warn("x4_auto_relay_unavailable", {
                interaction: interaction.id.slice(0, 8),
                requestId: interaction.requestId,
                reason: "interaction_not_question",
                interactionType: interaction.type,
            });
            return false;
        }

        try {
            await this.server.replyQuestion(interaction.requestId, [[prompt]]);
            logger.info("x4_auto_relay_sent", {
                interaction: interaction.id.slice(0, 8),
                requestId: interaction.requestId,
            });
            return true;
        } catch (error) {
            const message =
                error instanceof Error ? error.message : String(error);
            logger.warn("x4_auto_relay_failed", {
                interaction: interaction.id.slice(0, 8),
                requestId: interaction.requestId,
                error: message,
            });
            return false;
        }
    }

    private async enrichSummaryWithAgent(
        summary: Record<string, unknown>,
    ): Promise<Record<string, unknown>> {
        if (!this.server || !this.summarizerAgent) {
            return summary;
        }

        const result = await opencodeAgent.X4_summarize(this.server, {
            summary,
            summarizerAgent: this.summarizerAgent,
        });
        if (result.usedAgent && result.agent) {
            logger.info("x4_summary_agent_applied", {
                agent: result.agent,
            });
        } else if (result.error) {
            logger.warn("x4_summary_agent_failed", {
                agent: this.summarizerAgent,
                error: result.error,
            });
        }

        return result.summary;
    }
}
